### ISSUE TITLE
Cant upload media

### ISSUE THREAD

**Issue by mstdn** [uuttff8/Remmel#17]
Hello there!

First of all thank you for the hard work on an amazing app!

I did a fresh install of Lemmy on the domain meowrr.com and all seems to work. Only with the iOS app I cannot upload media and het an error.

Media uploading does work on Android & web

![image](https://user-images.githubusercontent.com/57602062/111902069-c784ba00-8a3b-11eb-8f29-120476ee50d0.png)

**Comment by uuttff8** [comment]
@mstdn verified, will fix soon

**Comment by mstdn** [comment]
You're the best!♥️

**Comment by uuttff8** [comment]
@mstdn should be fixed in next release
