### ISSUE TITLE
Not loading comments 

### ISSUE THREAD

**Issue by splacat** [uuttff8/Remmel#27]
Testing Remmel for iOS v1.5 from App Store with my Lemmy server v0.14.1.
Remmel is not loading any comments into Comments tab.
![2557FFE8-18D5-41BA-B139-03527BC2CE3E](https://user-images.githubusercontent.com/64102663/142759034-b66682fd-148f-484d-9be3-bb1301a247ac.jpeg)
![3EA175B3-675E-4423-AC6A-2529719603E1](https://user-images.githubusercontent.com/64102663/142759047-ae17e03c-98db-4e88-9f6a-90b383ef9bad.jpeg)

**Comment by hellojaccc** [comment]
I'm on `lemmy.ml`, comment tab works

**Comment by uuttff8** [comment]
New build already in the app store, the issue was lemmy backend sending incorrect date format! Now I handle this.

**Comment by splacat** [comment]
It's working fine now! thank you so much for your quick reaction and the new version!
