### ISSUE TITLE
Can't login to my lemmy account on lemmy.ml at all

### ISSUE THREAD

**Issue by Ne14k** [uuttff8/Remmel#30]
Where, it says accounts after clicking the instance (lemmy.ml). I put in my login info and the "Add" button will go from blue to grey and stay like that indefinately. 
![image](https://user-images.githubusercontent.com/95349960/151488744-37d47896-c13e-4628-9b20-066b08e61584.png)
If I say continue as a guest, then click login from the top right corner, put in my login info, the login button doesn't work. No matter how many times I click.
![image](https://user-images.githubusercontent.com/95349960/151488757-d5c1b4fd-cc1d-49fd-a210-7a9ee90bd2d3.png)
I've only tested this on lemmy.ml, so I cannot tell if this occurs anywhere else and I've already tried deleting and redownloading the app.

**Comment by GitOffMyBack** [comment]
I have the same problem trying to log into my instance at https://beehaw.org.

**Comment by andreatitolo** [comment]
Same issue here, deleting and redownloading the app doesn't work either. A strange thing I noticed today is that if I enter as guest and then try to login, it doesn't work, but if I go back and refresh some account-related stuff (like followed communities) I can see those that I am following, and I can even see my past comments if I cancel the prompt to login. 

However, any new account-related interaction is impossible as I am prompted to login every time.

**Comment by JesseKaczmarski** [comment]
I also have the same issue as well. I have had discussions on Lemmy about this in the past, pretty much everyone cannot use Remmel if it isn't already set up.

**Comment by dessalines** [comment]
ping @uuttff8 , we've had some API changes in recent releases since last Decemeber

The API diffs are in there: https://github.com/LemmyNet/lemmy/blob/main/RELEASES.md

**Comment by uuttff8** [comment]
ok guys new version will be available in a few days (1-2 days)

**Comment by JesseKaczmarski** [comment]
That’s great! Thanks for letting us know, and doing this.

**Comment by uuttff8** [comment]
I’ve updated my app to version 1.6 that supports Lemmy API v0.15.

**Comment by JesseKaczmarski** [comment]
Nice! I can finally login again. Appreciate you.

**Comment by andreatitolo** [comment]
Can confirm that login and every account-related feature works correctly now, thank you for the update :)

**Comment by nathancoooper** [comment]
Still having this issue on iOS

**Comment by myusernameisben** [comment]
Issue is still occurring on my side. Whenever I input username and password, it just hangs and does nothing further. Logging into lemmy.ml instance too.

**Comment by uuttff8** [comment]
@alex-ash @Ne14k 

Sorry for late response, I was very busy because of my politics of my country. This will be fixed in a week.

**Comment by alex-ash** [comment]
> @alex-ash @Ne14k
> 
> Sorry for late response, I was very busy because of my politics of my country. This will be fixed in a week.

Thank you so much for your work by the way.

**Comment by uuttff8** [comment]
@alex-ash 

Hello, new version available in the App Store, you can download it now. This should fix your issue.

**Comment by alex-ash** [comment]
> @alex-ash
> 
> Hello, new version available in the App Store, you can download it now. This should fix your issue.

Thank you so much! It works now.

**Comment by andreatitolo** [comment]
> @alex-ash
> 
> Hello, new version available in the App Store, you can download it now. This should fix your issue.

Can confirm too, instances other than lemmy.ml works as well. Thank you 🙏
