### ISSUE TITLE
Can’t login to Remmel

### ISSUE THREAD

**Issue by lenins-1st-cat** [uuttff8/Remmel#32]
Even though I’ve successfully signed up and logged in on lemmygrad.ml, I can’t login on the Remmel app. It gives me the following error message:

![6B7FA773-D4AB-4F7F-87CA-1AA7433C9AD5](https://user-images.githubusercontent.com/102253148/159771781-7a3673dc-49ac-423f-b716-d118a6ab7a57.jpeg)

**Comment by johnledezma34** [comment]
Same issue.

**Comment by hegginses** [comment]
Your issue here is that you're trying to log into your Lemmygrad.ml account on Lemmy.ml, the instances are separate. You need to add the lemmygrad.ml instance but you can't do it right now as of the time of me writing this comment as it appears there is a bug in the app.

**Comment by uuttff8** [comment]
@lenins-1st-cat @johnledezma34 

Hello, new version available in the App Store, you can download it now. This should fix your issue.
