### ISSUE TITLE
Cannot access non-lemmy.ml instance 

### ISSUE THREAD

**Issue by kermitstrontium** [uuttff8/Remmel#33]
Process:
1. Open app

2. Click plus in top right to add instance

3. Type a Lemmy url, such as https://Lemmygrad.ml/

4. Click enter on the keyboard

Result: the ‘add’ text in the top right briefly becomes a loading ball, then reverts to a greyed out ‘add’.

**Comment by hegginses** [comment]
Also having the exact same problem here. Have tried with multiple other instances and all produce the same results as described above.

**Comment by uuttff8** [comment]
@kermitstrontium @hegginses 

Hello, new version available in the App Store, you can download it now. This should fix your issue.

**Comment by kermitstrontium** [comment]
@uuttff8 thanks for your work—can confirm that the issue is fixed. I can now view and log into a different instance.
