### ISSUE TITLE
Continue with my instance does not work

### ISSUE THREAD

**Issue by GitOffMyBack** [uuttff8/Remmel#34]
Installed newest version from the Apple store, clicked Continue with my instance, typed in https://beehaw.org, clicked Done and nothing. The Add button is greyed out.

**Comment by nicfab** [comment]
I seconded

**Comment by uuttff8** [comment]
@nicfab @GitOffMyBack 

Hello, new version available in the App Store, you can download it now. This should fix your issue.

**Comment by nicfab** [comment]
> @nicfab @GitOffMyBack 
> 
> Hello, new version available in the App Store, you can download it now. This should fix your issue.

Thank you very much. 
Great work!
